server:
  port: 8084

spring:
  application:
    name: productMicroservice

  data:
    mongodb:
      host: localhost
      port: 27017
      database: novaShop
  profiles:
    active: dev

product:
  currencies:
    - INR
    - USD
    - EUR
